import { DEFAULT_SETTINGS, Preset } from './types';

export const PRESETS: Preset[] = [
  {
    id: 'default',
    name: 'Original / Neutral',
    description: 'Reset all adjustments to original image defaults',
    category: 'Utility',
    settings: { ...DEFAULT_SETTINGS },
  },
  {
    id: 'auto-enhance',
    name: 'Auto Enhance',
    description: 'Balanced intelligent tone, color vibrancy and micro-contrast boost',
    category: 'Enhancement',
    settings: {
      brightness: 4,
      contrast: 14,
      saturation: 16,
      exposure: 6,
      sharpness: 28,
      shadows: 18,
      highlights: -12,
      temperature: 2,
    },
  },
  {
    id: 'crisp-detail',
    name: 'Crisp Detail',
    description: 'High micro-contrast and edge sharpness with noise suppression',
    category: 'Enhancement',
    settings: {
      contrast: 18,
      sharpness: 55,
      denoise: 20,
      exposure: 4,
      highlights: -8,
      shadows: 10,
    },
  },
  {
    id: 'vivid-hdr',
    name: 'Vivid HDR',
    description: 'Punchy dynamic range with lifted shadows and saturated hues',
    category: 'Enhancement',
    settings: {
      contrast: 22,
      saturation: 32,
      exposure: 8,
      sharpness: 35,
      shadows: 30,
      highlights: -25,
      temperature: 4,
    },
  },
  {
    id: 'clean-portrait',
    name: 'Clean Portrait',
    description: 'Soft skin texture with delicate warmth and gentle edge sharpening',
    category: 'Enhancement',
    settings: {
      brightness: 6,
      contrast: 8,
      saturation: 10,
      exposure: 8,
      temperature: 12,
      denoise: 35,
      sharpness: 15,
      shadows: 14,
      highlights: -10,
    },
  },
  {
    id: 'cinematic-warm',
    name: 'Cinematic Sunset',
    description: 'Golden hour warmth with rich contrast and subtle vignette framing',
    category: 'Creative',
    settings: {
      contrast: 20,
      saturation: 22,
      temperature: 28,
      exposure: 2,
      shadows: 8,
      vignette: 24,
      sharpness: 20,
    },
  },
  {
    id: 'cool-nordic',
    name: 'Nordic Cool',
    description: 'Modern crisp Scandinavian aesthetic with cool undertones and deep contrast',
    category: 'Creative',
    settings: {
      contrast: 24,
      saturation: -12,
      temperature: -26,
      exposure: 4,
      sharpness: 30,
      shadows: 16,
      highlights: -18,
    },
  },
  {
    id: 'fine-art-bw',
    name: 'Fine Art B&W',
    description: 'Timeless high-contrast black and white with dramatic tonal depth',
    category: 'Creative',
    settings: {
      grayscale: 100,
      contrast: 34,
      exposure: 6,
      sharpness: 42,
      shadows: -10,
      highlights: 14,
      vignette: 18,
    },
  },
  {
    id: 'vintage-sepia',
    name: 'Vintage Sepia',
    description: 'Nostalgic warm sepia patina with soft vignette borders',
    category: 'Creative',
    settings: {
      sepia: 85,
      contrast: 15,
      brightness: 2,
      temperature: 18,
      vignette: 32,
      sharpness: 12,
    },
  },
];
